-- Schema lengkap untuk Nota App di Supabase
-- Jalankan script ini di Supabase SQL Editor untuk membuat semua tabel

-- ============================================
-- RBAC (Role-Based Access Control) Tables
-- ============================================

-- Tabel Users
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabel Roles
CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabel Permissions
CREATE TABLE IF NOT EXISTS permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    resource VARCHAR(100) NOT NULL,
    action VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabel Role Permissions (Many-to-Many)
CREATE TABLE IF NOT EXISTS role_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    permission_id BIGINT NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(role_id, permission_id)
);

-- Tabel User Roles (Many-to-Many)
CREATE TABLE IF NOT EXISTS user_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, role_id)
);

-- ============================================
-- Business Tables
-- ============================================

-- Tabel Data Barang
CREATE TABLE IF NOT EXISTS data_barang (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(100) DEFAULT '',
    initial_quantity INT DEFAULT 0,
    quantity INT DEFAULT 0,
    price DECIMAL(15, 2) DEFAULT 0,
    type TEXT DEFAULT 'mutasi' CHECK (type IN ('mutasi', 'bengkel')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabel Data Jasa
CREATE TABLE IF NOT EXISTS data_jasa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(15, 2) DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabel Data Mekanik
CREATE TABLE IF NOT EXISTS data_mekanik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabel Data Transaksi
CREATE TABLE IF NOT EXISTS data_transaksi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number VARCHAR(100) NOT NULL UNIQUE,
    date DATE NOT NULL,
    customer_name VARCHAR(255) NOT NULL,
    customer_phone VARCHAR(50) DEFAULT '',
    customer_km_masuk VARCHAR(50) DEFAULT '',
    customer_mobil VARCHAR(255) DEFAULT '',
    customer_plat_nomor VARCHAR(50) DEFAULT '',
    customer_tipe TEXT DEFAULT 'umum' CHECK (customer_tipe IN ('umum', 'perusahaan')),
    customer_mekanik VARCHAR(255) DEFAULT '',
    customer_mekaniks JSONB DEFAULT NULL,
    items JSONB NOT NULL,
    total DECIMAL(15, 2) NOT NULL DEFAULT 0,
    keterangan TEXT DEFAULT NULL,
    saved_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- Indexes untuk RBAC Tables
-- ============================================

-- Indexes untuk users
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_active ON users(is_active);

-- Indexes untuk roles
CREATE INDEX IF NOT EXISTS idx_roles_name ON roles(name);

-- Indexes untuk permissions
CREATE INDEX IF NOT EXISTS idx_permissions_resource ON permissions(resource);
CREATE INDEX IF NOT EXISTS idx_permissions_action ON permissions(action);
CREATE INDEX IF NOT EXISTS idx_permissions_name ON permissions(name);

-- Indexes untuk role_permissions
CREATE INDEX IF NOT EXISTS idx_role_permissions_role_id ON role_permissions(role_id);
CREATE INDEX IF NOT EXISTS idx_role_permissions_permission_id ON role_permissions(permission_id);

-- Indexes untuk user_roles
CREATE INDEX IF NOT EXISTS idx_user_roles_user_id ON user_roles(user_id);
CREATE INDEX IF NOT EXISTS idx_user_roles_role_id ON user_roles(role_id);

-- ============================================
-- Indexes untuk Business Tables
-- ============================================

-- Indexes untuk data_barang
CREATE INDEX IF NOT EXISTS idx_data_barang_code ON data_barang(code);
CREATE INDEX IF NOT EXISTS idx_data_barang_type ON data_barang(type);
CREATE INDEX IF NOT EXISTS idx_data_barang_name ON data_barang(name);

-- Indexes untuk data_jasa
CREATE INDEX IF NOT EXISTS idx_data_jasa_name ON data_jasa(name);

-- Indexes untuk data_mekanik
CREATE INDEX IF NOT EXISTS idx_data_mekanik_name ON data_mekanik(name);

-- Indexes untuk data_transaksi
CREATE INDEX IF NOT EXISTS idx_data_transaksi_invoice_number ON data_transaksi(invoice_number);
CREATE INDEX IF NOT EXISTS idx_data_transaksi_date ON data_transaksi(date);
CREATE INDEX IF NOT EXISTS idx_data_transaksi_customer_name ON data_transaksi(customer_name);
CREATE INDEX IF NOT EXISTS idx_data_transaksi_saved_at ON data_transaksi(saved_at);

-- ============================================
-- Functions dan Triggers
-- ============================================

-- Function untuk updated_at trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Triggers untuk updated_at (RBAC Tables)
CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_roles_updated_at BEFORE UPDATE ON roles FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_permissions_updated_at BEFORE UPDATE ON permissions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Triggers untuk updated_at (Business Tables)
CREATE TRIGGER update_data_barang_updated_at BEFORE UPDATE ON data_barang FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_data_jasa_updated_at BEFORE UPDATE ON data_jasa FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_data_mekanik_updated_at BEFORE UPDATE ON data_mekanik FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_data_transaksi_updated_at BEFORE UPDATE ON data_transaksi FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- Row Level Security (RLS)
-- ============================================

-- Enable RLS on all tables
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE role_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE data_barang ENABLE ROW LEVEL SECURITY;
ALTER TABLE data_jasa ENABLE ROW LEVEL SECURITY;
ALTER TABLE data_mekanik ENABLE ROW LEVEL SECURITY;
ALTER TABLE data_transaksi ENABLE ROW LEVEL SECURITY;

-- Policies untuk RBAC Tables (sesuaikan dengan kebutuhan keamanan Anda)
CREATE POLICY "Enable all operations for users" ON users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for roles" ON roles FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for permissions" ON permissions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for role_permissions" ON role_permissions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for user_roles" ON user_roles FOR ALL USING (true) WITH CHECK (true);

-- Policies untuk Business Tables (sesuaikan dengan kebutuhan keamanan Anda)
CREATE POLICY "Enable all operations for data_barang" ON data_barang FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for data_jasa" ON data_jasa FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for data_mekanik" ON data_mekanik FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for data_transaksi" ON data_transaksi FOR ALL USING (true) WITH CHECK (true);

-- ============================================
-- Default Data
-- ============================================

-- Insert default roles
INSERT INTO roles (name, description) VALUES
('admin', 'Administrator dengan akses penuh'),
('manager', 'Manager dengan akses ke sebagian besar fitur'),
('kasir', 'Kasir dengan akses terbatas ke POS dan transaksi'),
('mekanik', 'Mekanik dengan akses ke data transaksi terbatas')
ON CONFLICT (name) DO NOTHING;

-- Insert default permissions
INSERT INTO permissions (name, description, resource, action) VALUES
-- User Management
('users.create', 'Membuat user baru', 'users', 'create'),
('users.read', 'Melihat data user', 'users', 'read'),
('users.update', 'Mengupdate data user', 'users', 'update'),
('users.delete', 'Menghapus user', 'users', 'delete'),

-- Role Management
('roles.create', 'Membuat role baru', 'roles', 'create'),
('roles.read', 'Melihat data role', 'roles', 'read'),
('roles.update', 'Mengupdate data role', 'roles', 'update'),
('roles.delete', 'Menghapus role', 'roles', 'delete'),

-- Permission Management
('permissions.create', 'Membuat permission baru', 'permissions', 'create'),
('permissions.read', 'Melihat data permission', 'permissions', 'read'),
('permissions.update', 'Mengupdate data permission', 'permissions', 'update'),
('permissions.delete', 'Menghapus permission', 'permissions', 'delete'),

-- Data Barang
('barang.create', 'Membuat data barang', 'barang', 'create'),
('barang.read', 'Melihat data barang', 'barang', 'read'),
('barang.update', 'Mengupdate data barang', 'barang', 'update'),
('barang.delete', 'Menghapus data barang', 'barang', 'delete'),

-- Data Jasa
('jasa.create', 'Membuat data jasa', 'jasa', 'create'),
('jasa.read', 'Melihat data jasa', 'jasa', 'read'),
('jasa.update', 'Mengupdate data jasa', 'jasa', 'update'),
('jasa.delete', 'Menghapus data jasa', 'jasa', 'delete'),

-- Data Mekanik
('mekanik.create', 'Membuat data mekanik', 'mekanik', 'create'),
('mekanik.read', 'Melihat data mekanik', 'mekanik', 'read'),
('mekanik.update', 'Mengupdate data mekanik', 'mekanik', 'update'),
('mekanik.delete', 'Menghapus data mekanik', 'mekanik', 'delete'),

-- Data Transaksi
('transaksi.create', 'Membuat transaksi', 'transaksi', 'create'),
('transaksi.read', 'Melihat data transaksi', 'transaksi', 'read'),
('transaksi.update', 'Mengupdate data transaksi', 'transaksi', 'update'),
('transaksi.delete', 'Menghapus data transaksi', 'transaksi', 'delete'),

-- POS
('pos.access', 'Akses ke halaman POS', 'pos', 'access'),

-- Dashboard
('dashboard.access', 'Akses ke dashboard', 'dashboard', 'access')
ON CONFLICT (name) DO NOTHING;

-- Assign all permissions to admin role
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, permissions p
WHERE r.name = 'admin'
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- Assign limited permissions to kasir role
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, permissions p
WHERE r.name = 'kasir' AND p.action IN ('read', 'create') AND p.resource IN ('barang', 'jasa', 'mekanik', 'transaksi', 'pos')
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- Assign limited permissions to mekanik role
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, permissions p
WHERE r.name = 'mekanik' AND p.action IN ('read') AND p.resource IN ('transaksi', 'mekanik')
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- Create default admin user (password: admin123)
INSERT INTO users (email, name, password_hash) VALUES
('admin@nota-app.com', 'Administrator', '$2b$10$rOzJqQjQjQjQjQjQjQjQjOzJqQjQjQjQjQjQjQjQjQjQjQjQjQjQjQjQjQ')
ON CONFLICT (email) DO NOTHING;

-- Assign admin role to default admin user
INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id
FROM users u, roles r
WHERE u.email = 'admin@nota-app.com' AND r.name = 'admin'
ON CONFLICT (user_id, role_id) DO NOTHING;