-- Migration 001: Create RBAC Tables
-- Jalankan migration ini di Supabase SQL Editor

-- ============================================
-- RBAC (Role-Based Access Control) Tables
-- ============================================

-- Tabel Users
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabel Roles
CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabel Permissions
CREATE TABLE IF NOT EXISTS permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    resource VARCHAR(100) NOT NULL,
    action VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabel Role Permissions (Many-to-Many)
CREATE TABLE IF NOT EXISTS role_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    permission_id BIGINT NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(role_id, permission_id)
);

-- Tabel User Roles (Many-to-Many)
CREATE TABLE IF NOT EXISTS user_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, role_id)
);

-- ============================================
-- Indexes untuk RBAC Tables
-- ============================================

-- Indexes untuk users
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_active ON users(is_active);

-- Indexes untuk roles
CREATE INDEX IF NOT EXISTS idx_roles_name ON roles(name);

-- Indexes untuk permissions
CREATE INDEX IF NOT EXISTS idx_permissions_resource ON permissions(resource);
CREATE INDEX IF NOT EXISTS idx_permissions_action ON permissions(action);
CREATE INDEX IF NOT EXISTS idx_permissions_name ON permissions(name);

-- Indexes untuk role_permissions
CREATE INDEX IF NOT EXISTS idx_role_permissions_role_id ON role_permissions(role_id);
CREATE INDEX IF NOT EXISTS idx_role_permissions_permission_id ON role_permissions(permission_id);

-- Indexes untuk user_roles
CREATE INDEX IF NOT EXISTS idx_user_roles_user_id ON user_roles(user_id);
CREATE INDEX IF NOT EXISTS idx_user_roles_role_id ON user_roles(role_id);

-- ============================================
-- Functions dan Triggers untuk RBAC Tables
-- ============================================

-- Function untuk updated_at trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Triggers untuk updated_at (RBAC Tables)
DROP TRIGGER IF EXISTS update_users_updated_at ON users;
CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_roles_updated_at ON roles;
CREATE TRIGGER update_roles_updated_at BEFORE UPDATE ON roles FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_permissions_updated_at ON permissions;
CREATE TRIGGER update_permissions_updated_at BEFORE UPDATE ON permissions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- Row Level Security (RLS) untuk RBAC Tables
-- ============================================

-- Enable RLS on RBAC tables
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE role_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_roles ENABLE ROW LEVEL SECURITY;

-- Policies untuk RBAC Tables (sesuaikan dengan kebutuhan keamanan Anda)
DROP POLICY IF EXISTS "Enable all operations for users" ON users;
CREATE POLICY "Enable all operations for users" ON users FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Enable all operations for roles" ON roles;
CREATE POLICY "Enable all operations for roles" ON roles FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Enable all operations for permissions" ON permissions;
CREATE POLICY "Enable all operations for permissions" ON permissions FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Enable all operations for role_permissions" ON role_permissions;
CREATE POLICY "Enable all operations for role_permissions" ON role_permissions FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Enable all operations for user_roles" ON user_roles;
CREATE POLICY "Enable all operations for user_roles" ON user_roles FOR ALL USING (true) WITH CHECK (true);

-- ============================================
-- Default Data untuk RBAC
-- ============================================

-- Insert default roles
INSERT INTO roles (name, description) VALUES 
('admin', 'Administrator dengan akses penuh'),
('manager', 'Manager dengan akses ke sebagian besar fitur'),
('kasir', 'Kasir dengan akses terbatas ke POS dan transaksi'),
('mekanik', 'Mekanik dengan akses ke data transaksi terbatas')
ON CONFLICT (name) DO NOTHING;

-- Insert default permissions
INSERT INTO permissions (name, description, resource, action) VALUES 
-- User Management
('users.create', 'Membuat user baru', 'users', 'create'),
('users.read', 'Melihat data user', 'users', 'read'),
('users.update', 'Mengupdate data user', 'users', 'update'),
('users.delete', 'Menghapus user', 'users', 'delete'),

-- Role Management
('roles.create', 'Membuat role baru', 'roles', 'create'),
('roles.read', 'Melihat data role', 'roles', 'read'),
('roles.update', 'Mengupdate data role', 'roles', 'update'),
('roles.delete', 'Menghapus role', 'roles', 'delete'),

-- Permission Management
('permissions.create', 'Membuat permission baru', 'permissions', 'create'),
('permissions.read', 'Melihat data permission', 'permissions', 'read'),
('permissions.update', 'Mengupdate data permission', 'permissions', 'update'),
('permissions.delete', 'Menghapus permission', 'permissions', 'delete'),

-- POS
('pos.access', 'Akses ke halaman POS', 'pos', 'access'),

-- Dashboard
('dashboard.access', 'Akses ke dashboard', 'dashboard', 'access')
ON CONFLICT (name) DO NOTHING;

-- Assign all permissions to admin role
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id 
FROM roles r, permissions p 
WHERE r.name = 'admin'
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- Create default admin user (password: admin123)
INSERT INTO users (email, name, password_hash) VALUES 
('admin@nota-app.com', 'Administrator', '$2b$10$rOzJqQjQjQjQjQjQjQjQjOzJqQjQjQjQjQjQjQjQjQjQjQjQjQjQjQjQjQ')
ON CONFLICT (email) DO NOTHING;

-- Assign admin role to default admin user
INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id 
FROM users u, roles r 
WHERE u.email = 'admin@nota-app.com' AND r.name = 'admin'
ON CONFLICT (user_id, role_id) DO NOTHING;