-- Migration 002.1: Create Data Barang Table
-- Jalankan migration ini di Supabase SQL Editor setelah migration 001

-- ============================================
-- Tabel Data Barang
-- ============================================

CREATE TABLE IF NOT EXISTS data_barang (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(100) DEFAULT '',
    initial_quantity INT DEFAULT 0,
    quantity INT DEFAULT 0,
    price DECIMAL(15, 2) DEFAULT 0,
    type TEXT DEFAULT 'mutasi' CHECK (type IN ('mutasi', 'bengkel')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- Indexes untuk data_barang
-- ============================================

CREATE INDEX IF NOT EXISTS idx_data_barang_code ON data_barang(code);
CREATE INDEX IF NOT EXISTS idx_data_barang_type ON data_barang(type);
CREATE INDEX IF NOT EXISTS idx_data_barang_name ON data_barang(name);

-- ============================================
-- Trigger untuk data_barang
-- ============================================

DROP TRIGGER IF EXISTS update_data_barang_updated_at ON data_barang;
CREATE TRIGGER update_data_barang_updated_at BEFORE UPDATE ON data_barang FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- Row Level Security (RLS) untuk data_barang
-- ============================================

ALTER TABLE data_barang ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable all operations for data_barang" ON data_barang;
CREATE POLICY "Enable all operations for data_barang" ON data_barang FOR ALL USING (true) WITH CHECK (true);

-- ============================================
-- Permissions untuk Data Barang
-- ============================================

INSERT INTO permissions (name, description, resource, action) VALUES 
('barang.create', 'Membuat data barang', 'barang', 'create'),
('barang.read', 'Melihat data barang', 'barang', 'read'),
('barang.update', 'Mengupdate data barang', 'barang', 'update'),
('barang.delete', 'Menghapus data barang', 'barang', 'delete')
ON CONFLICT (name) DO NOTHING;