-- Migration 002.2: Create Data Jasa Table
-- Jalankan migration ini di Supabase SQL Editor setelah migration 002.1

-- ============================================
-- Tabel Data Jasa
-- ============================================

CREATE TABLE IF NOT EXISTS data_jasa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(15, 2) DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- Indexes untuk data_jasa
-- ============================================

CREATE INDEX IF NOT EXISTS idx_data_jasa_name ON data_jasa(name);

-- ============================================
-- Trigger untuk data_jasa
-- ============================================

CREATE TRIGGER update_data_jasa_updated_at BEFORE UPDATE ON data_jasa FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- Row Level Security (RLS) untuk data_jasa
-- ============================================

ALTER TABLE data_jasa ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all operations for data_jasa" ON data_jasa FOR ALL USING (true) WITH CHECK (true);

-- ============================================
-- Permissions untuk Data Jasa
-- ============================================

INSERT INTO permissions (name, description, resource, action) VALUES 
('jasa.create', 'Membuat data jasa', 'jasa', 'create'),
('jasa.read', 'Melihat data jasa', 'jasa', 'read'),
('jasa.update', 'Mengupdate data jasa', 'jasa', 'update'),
('jasa.delete', 'Menghapus data jasa', 'jasa', 'delete')
ON CONFLICT (name) DO NOTHING;