-- Migration 002.3: Create Data Mekanik Table
-- Jalankan migration ini di Supabase SQL Editor setelah migration 002.2

-- ============================================
-- Tabel Data Mekanik
-- ============================================

CREATE TABLE IF NOT EXISTS data_mekanik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- Indexes untuk data_mekanik
-- ============================================

CREATE INDEX IF NOT EXISTS idx_data_mekanik_name ON data_mekanik(name);

-- ============================================
-- Trigger untuk data_mekanik
-- ============================================

CREATE TRIGGER update_data_mekanik_updated_at BEFORE UPDATE ON data_mekanik FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- Row Level Security (RLS) untuk data_mekanik
-- ============================================

ALTER TABLE data_mekanik ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all operations for data_mekanik" ON data_mekanik FOR ALL USING (true) WITH CHECK (true);

-- ============================================
-- Permissions untuk Data Mekanik
-- ============================================

INSERT INTO permissions (name, description, resource, action) VALUES 
('mekanik.create', 'Membuat data mekanik', 'mekanik', 'create'),
('mekanik.read', 'Melihat data mekanik', 'mekanik', 'read'),
('mekanik.update', 'Mengupdate data mekanik', 'mekanik', 'update'),
('mekanik.delete', 'Menghapus data mekanik', 'mekanik', 'delete')
ON CONFLICT (name) DO NOTHING;