-- Migration 002.4: Create Data Transaksi Table
-- Jalankan migration ini di Supabase SQL Editor setelah migration 002.3

-- ============================================
-- Tabel Data Transaksi
-- ============================================

CREATE TABLE IF NOT EXISTS data_transaksi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number VARCHAR(100) NOT NULL UNIQUE,
    date DATE NOT NULL,
    customer_name VARCHAR(255) NOT NULL,
    customer_phone VARCHAR(50) DEFAULT '',
    customer_km_masuk VARCHAR(50) DEFAULT '',
    customer_mobil VARCHAR(255) DEFAULT '',
    customer_plat_nomor VARCHAR(50) DEFAULT '',
    customer_tipe TEXT DEFAULT 'umum' CHECK (customer_tipe IN ('umum', 'perusahaan')),
    customer_mekanik VARCHAR(255) DEFAULT '',
    customer_mekaniks JSONB DEFAULT NULL,
    items JSONB NOT NULL,
    total DECIMAL(15, 2) NOT NULL DEFAULT 0,
    keterangan TEXT DEFAULT NULL,
    saved_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- Indexes untuk data_transaksi
-- ============================================

CREATE INDEX IF NOT EXISTS idx_data_transaksi_invoice_number ON data_transaksi(invoice_number);
CREATE INDEX IF NOT EXISTS idx_data_transaksi_date ON data_transaksi(date);
CREATE INDEX IF NOT EXISTS idx_data_transaksi_customer_name ON data_transaksi(customer_name);
CREATE INDEX IF NOT EXISTS idx_data_transaksi_saved_at ON data_transaksi(saved_at);

-- ============================================
-- Trigger untuk data_transaksi
-- ============================================

CREATE TRIGGER update_data_transaksi_updated_at BEFORE UPDATE ON data_transaksi FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- Row Level Security (RLS) untuk data_transaksi
-- ============================================

ALTER TABLE data_transaksi ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all operations for data_transaksi" ON data_transaksi FOR ALL USING (true) WITH CHECK (true);

-- ============================================
-- Permissions untuk Data Transaksi
-- ============================================

INSERT INTO permissions (name, description, resource, action) VALUES 
('transaksi.create', 'Membuat transaksi', 'transaksi', 'create'),
('transaksi.read', 'Melihat data transaksi', 'transaksi', 'read'),
('transaksi.update', 'Mengupdate data transaksi', 'transaksi', 'update'),
('transaksi.delete', 'Menghapus data transaksi', 'transaksi', 'delete')
ON CONFLICT (name) DO NOTHING;