-- Create mechanic_settings table for individual mechanic commission settings
CREATE TABLE IF NOT EXISTS mechanic_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mechanic_id BIGINT NOT NULL REFERENCES data_mekanik(id) ON DELETE CASCADE,
    shop_cut_percentage DECIMAL(5,2) NOT NULL DEFAULT 50.00, -- Potongan toko (0-100)
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(mechanic_id)
);

-- Create global_settings table for global shop cut settings
CREATE TABLE IF NOT EXISTS global_settings (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    setting_key VARCHAR(100) NOT NULL UNIQUE,
    setting_value TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Insert default global settings
INSERT INTO global_settings (setting_key, setting_value, description) VALUES
    ('default_shop_cut_percentage', '50.00', 'Default potongan toko untuk semua mekanik (dalam persen)'),
    ('mechanic_commission_calculation', 'after_shop_cut', 'Metode perhitungan komisi: after_shop_cut atau before_shop_cut'),
    ('enable_custom_mechanic_settings', 'true', 'Apakah mengaktifkan pengaturan potongan per mekanik')
ON CONFLICT (setting_key) DO NOTHING;

-- Create index for better performance
CREATE INDEX IF NOT EXISTS idx_mechanic_settings_mechanic_id ON mechanic_settings(mechanic_id);
CREATE INDEX IF NOT EXISTS idx_global_settings_key ON global_settings(setting_key);

-- Create function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create triggers for updated_at
DROP TRIGGER IF EXISTS update_mechanic_settings_updated_at ON mechanic_settings;
CREATE TRIGGER update_mechanic_settings_updated_at 
    BEFORE UPDATE ON mechanic_settings 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_global_settings_updated_at ON global_settings;
CREATE TRIGGER update_global_settings_updated_at 
    BEFORE UPDATE ON global_settings 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Add RLS policies
ALTER TABLE mechanic_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE global_settings ENABLE ROW LEVEL SECURITY;

-- Policy for mechanic_settings - only authenticated users can read
DROP POLICY IF EXISTS "Authenticated users can view mechanic settings" ON mechanic_settings;
CREATE POLICY "Authenticated users can view mechanic settings" ON mechanic_settings
    FOR SELECT USING (auth.role() = 'authenticated');

-- Policy for mechanic_settings - only authenticated users can modify
DROP POLICY IF EXISTS "Authenticated users can modify mechanic settings" ON mechanic_settings;
CREATE POLICY "Authenticated users can modify mechanic settings" ON mechanic_settings
    FOR ALL USING (auth.role() = 'authenticated');

-- Policy for global_settings - only authenticated users can read
DROP POLICY IF EXISTS "Authenticated users can view global settings" ON global_settings;
CREATE POLICY "Authenticated users can view global settings" ON global_settings
    FOR SELECT USING (auth.role() = 'authenticated');

-- Policy for global_settings - only admin users can modify
DROP POLICY IF EXISTS "Admin users can modify global settings" ON global_settings;
CREATE POLICY "Admin users can modify global settings" ON global_settings
    FOR ALL USING (
        auth.role() = 'authenticated' 
        AND EXISTS (
            SELECT 1 FROM auth.users 
            WHERE auth.users.id = auth.uid() 
            AND raw_user_meta_data->>'role' = 'admin'
        )
    );