-- Create financial_reports table for storing generated financial reports
CREATE TABLE IF NOT EXISTS financial_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_type VARCHAR(50) NOT NULL, -- 'profit_loss', 'balance_sheet', 'cash_flow'
    report_period VARCHAR(20) NOT NULL, -- 'monthly', 'quarterly', 'yearly'
    period_start_date DATE NOT NULL,
    period_end_date DATE NOT NULL,
    report_data JSONB NOT NULL, -- Store report data as JSON
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by UUID REFERENCES auth.users(id)
);

-- Create chart_of_accounts table for account structure
CREATE TABLE IF NOT EXISTS chart_of_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_code VARCHAR(20) NOT NULL UNIQUE,
    account_name VARCHAR(200) NOT NULL,
    account_type VARCHAR(50) NOT NULL, -- 'asset', 'liability', 'equity', 'revenue', 'expense'
    parent_account_id BIGINT REFERENCES chart_of_accounts(id),
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create journal_entries table for recording all financial transactions
CREATE TABLE IF NOT EXISTS journal_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_number VARCHAR(50) NOT NULL UNIQUE,
    entry_date DATE NOT NULL,
    description TEXT,
    reference_type VARCHAR(50), -- 'transaction', 'purchase', 'return', 'adjustment'
    reference_id VARCHAR(100), -- ID of related transaction
    total_amount DECIMAL(15,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by UUID REFERENCES auth.users(id)
);

-- Create journal_entry_lines table for double-entry bookkeeping
CREATE TABLE IF NOT EXISTS journal_entry_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_entry_id BIGINT NOT NULL REFERENCES journal_entries(id) ON DELETE CASCADE,
    account_id BIGINT NOT NULL REFERENCES chart_of_accounts(id),
    description TEXT,
    debit_amount DECIMAL(15,2) NOT NULL DEFAULT 0,
    credit_amount DECIMAL(15,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Insert default chart of accounts
INSERT INTO chart_of_accounts (account_code, account_name, account_type) VALUES
    -- Assets
    ('100', 'Kas dan Bank', 'asset'),
    ('110', 'Kas Tunai', 'asset'),
    ('120', 'Bank', 'asset'),
    ('130', 'Piutang Usaha', 'asset'),
    ('140', 'Persediaan Barang', 'asset'),
    ('150', 'Peralatan', 'asset'),
    
    -- Liabilities
    ('200', 'Hutang Usaha', 'liability'),
    ('210', 'Hutang Pembelian', 'liability'),
    ('220', 'Hutang Gaji', 'liability'),
    
    -- Equity
    ('300', 'Modal', 'equity'),
    ('310', 'Modal Awal', 'equity'),
    ('320', 'Laba Tahun Berjalan', 'equity'),
    ('330', 'Prive', 'equity'),
    
    -- Revenue
    ('400', 'Pendapatan Jasa', 'revenue'),
    ('410', 'Pendapatan Penjualan Barang', 'revenue'),
    ('420', 'Pendapatan Lain-lain', 'revenue'),
    
    -- Expenses
    ('500', 'Harga Pokok Penjualan', 'expense'),
    ('510', 'Biaya Pembelian', 'expense'),
    ('520', 'Biaya Gaji Mekanik', 'expense'),
    ('530', 'Biaya Operasional', 'expense'),
    ('540', 'Biaya Administrasi', 'expense'),
    ('550', 'Biaya Penyusutan', 'expense')
ON CONFLICT (account_code) DO NOTHING;

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_financial_reports_type_period ON financial_reports(report_type, report_period);
CREATE INDEX IF NOT EXISTS idx_financial_reports_dates ON financial_reports(period_start_date, period_end_date);
CREATE INDEX IF NOT EXISTS idx_chart_of_accounts_type ON chart_of_accounts(account_type);
CREATE INDEX IF NOT EXISTS idx_journal_entries_date ON journal_entries(entry_date);
CREATE INDEX IF NOT EXISTS idx_journal_entry_lines_entry ON journal_entry_lines(journal_entry_id);
CREATE INDEX IF NOT EXISTS idx_journal_entry_lines_account ON journal_entry_lines(account_id);

-- Create function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create triggers for updated_at
DROP TRIGGER IF EXISTS update_financial_reports_updated_at ON financial_reports;
CREATE TRIGGER update_financial_reports_updated_at 
    BEFORE UPDATE ON financial_reports 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_chart_of_accounts_updated_at ON chart_of_accounts;
CREATE TRIGGER update_chart_of_accounts_updated_at 
    BEFORE UPDATE ON chart_of_accounts 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Add RLS policies
ALTER TABLE financial_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE chart_of_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE journal_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE journal_entry_lines ENABLE ROW LEVEL SECURITY;

-- Policy for financial_reports
DROP POLICY IF EXISTS "Authenticated users can view financial reports" ON financial_reports;
CREATE POLICY "Authenticated users can view financial reports" ON financial_reports
    FOR SELECT USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Authenticated users can modify financial reports" ON financial_reports;
CREATE POLICY "Authenticated users can modify financial reports" ON financial_reports
    FOR ALL USING (auth.role() = 'authenticated');

-- Policy for chart_of_accounts
DROP POLICY IF EXISTS "Authenticated users can view chart of accounts" ON chart_of_accounts;
CREATE POLICY "Authenticated users can view chart of accounts" ON chart_of_accounts
    FOR SELECT USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Authenticated users can modify chart of accounts" ON chart_of_accounts;
CREATE POLICY "Authenticated users can modify chart of accounts" ON chart_of_accounts
    FOR ALL USING (auth.role() = 'authenticated');

-- Policy for journal_entries
DROP POLICY IF EXISTS "Authenticated users can view journal entries" ON journal_entries;
CREATE POLICY "Authenticated users can view journal entries" ON journal_entries
    FOR SELECT USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Authenticated users can modify journal entries" ON journal_entries;
CREATE POLICY "Authenticated users can modify journal entries" ON journal_entries
    FOR ALL USING (auth.role() = 'authenticated');

-- Policy for journal_entry_lines
DROP POLICY IF EXISTS "Authenticated users can view journal entry lines" ON journal_entry_lines;
CREATE POLICY "Authenticated users can view journal entry lines" ON journal_entry_lines
    FOR SELECT USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Authenticated users can modify journal entry lines" ON journal_entry_lines;
CREATE POLICY "Authenticated users can modify journal entry lines" ON journal_entry_lines
    FOR ALL USING (auth.role() = 'authenticated');