create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  date date not null default current_date,
  description text not null,
  amount numeric not null check (amount > 0),
  category text not null,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_by uuid references auth.users(id)
);

-- Enable RLS
alter table public.expenses enable row level security;

-- Policies
create policy "Enable read access for authenticated users"
on public.expenses for select
to authenticated
using (true);

create policy "Enable insert access for authenticated users"
on public.expenses for insert
to authenticated
with check (auth.uid() = created_by);

create policy "Enable update access for users based on created_by"
on public.expenses for update
to authenticated
using (auth.uid() = created_by);

create policy "Enable delete access for users based on created_by"
on public.expenses for delete
to authenticated
using (auth.uid() = created_by);
